Repository EternalCodeTeam/DiscordOfficer, pull requests merged in 2023-04, with the labels that each got.

#64 GH-64 Implement drivers and ormlite
  .dockerignore
  .github/workflows/dockerHub.yml
  .github/workflows/gradle.yml
  .gitignore
  build.gradle.kts
  checkstyle/checkstyle.xml
  checkstyle/suppressions.xml
  docker/java17.dockerfile
  docker/java19.dockerfile
  src/main/java/com/eternalcode/discordapp/DiscordApp.java
  src/main/java/com/eternalcode/discordapp/command/AvatarCommand.java
  src/main/java/com/eternalcode/discordapp/command/BanCommand.java
  src/main/java/com/eternalcode/discordapp/command/BotInfoCommand.java
  src/main/java/com/eternalcode/discordapp/command/ClearCommand.java
  src/main/java/com/eternalcode/discordapp/command/CooldownCommand.java
  src/main/java/com/eternalcode/discordapp/command/KickCommand.java
  src/main/java/com/eternalcode/discordapp/command/PingCommand.java
  src/main/java/com/eternalcode/discordapp/command/ServerCommand.java
  src/main/java/com/eternalcode/discordapp/config/AppConfig.java
  src/main/java/com/eternalcode/discordapp/config/ConfigManager.java
  src/main/java/com/eternalcode/discordapp/config/DatabaseConfig.java
  src/main/java/com/eternalcode/discordapp/database/DatabaseManager.java
  src/main/java/com/eternalcode/discordapp/database/DatabaseType.java
  src/main/java/com/eternalcode/discordapp/database/repository/AbstractRepository.java
  src/main/java/com/eternalcode/discordapp/experience/Experience.java
  src/main/java/com/eternalcode/discordapp/experience/ExperienceConfig.java
  src/main/java/com/eternalcode/discordapp/experience/ExperienceRepository.java
  src/main/java/com/eternalcode/discordapp/experience/ExperienceRepositoryImpl.java
  src/main/java/com/eternalcode/discordapp/experience/ExperienceUtil.java
  src/main/java/com/eternalcode/discordapp/experience/ExperienceWrapper.java
  src/main/java/com/eternalcode/discordapp/experience/listener/ExperienceMessageListener.java
  src/main/java/com/eternalcode/discordapp/guildstats/GuildStatisticsService.java
  src/main/java/com/eternalcode/discordapp/user/User.java
  src/main/java/com/eternalcode/discordapp/user/UserRepository.java
  src/main/java/com/eternalcode/discordapp/user/UserRepositoryImpl.java
  src/main/java/com/eternalcode/discordapp/user/UserWrapper.java
Labels: PR: unreviewed

#74 GH-74 GitHub review
  build.gradle.kts
  src/main/java/com/eternalcode/discordapp/DiscordApp.java
  src/main/java/com/eternalcode/discordapp/command/MinecraftServerInfoCommand.java
  src/main/java/com/eternalcode/discordapp/config/AppConfig.java
  src/main/java/com/eternalcode/discordapp/experience/listener/ExperienceMessageListener.java
  src/main/java/com/eternalcode/discordapp/filter/FilterMessageEmbedController.java
  src/main/java/com/eternalcode/discordapp/filter/FilterResult.java
  src/main/java/com/eternalcode/discordapp/review/GitHubReviewCommand.java
  src/main/java/com/eternalcode/discordapp/review/GitHubReviewService.java
  src/main/java/com/eternalcode/discordapp/review/GitHubReviewTask.java
  src/main/java/com/eternalcode/discordapp/review/GitHubReviewUtil.java
  src/test/java/com/eternalcode/discordapp/review/GitHubReviewUtilTest.java
Labels: PR: reviewed-approved

#77 GH-77 Archive instead of delete forum post
  src/main/java/com/eternalcode/discordapp/review/GitHubReviewService.java
Labels: PR: partially-approved

#78 GH-78 Store moment of mention to reduce refresh mention state time.
  build.gradle.kts
  checkstyle/suppressions.xml
  src/main/java/com/eternalcode/discordapp/DiscordApp.java
  src/main/java/com/eternalcode/discordapp/review/GitHubPullRequest.java
  src/main/java/com/eternalcode/discordapp/review/GitHubReviewMentionRepository.java
  src/main/java/com/eternalcode/discordapp/review/GitHubReviewMentionRepositoryImpl.java
  src/main/java/com/eternalcode/discordapp/review/GitHubReviewService.java
  src/main/java/com/eternalcode/discordapp/review/GitHubReviewUtil.java
  src/test/java/com/eternalcode/discordapp/review/GitHubReviewUtilTest.java
Labels: PR: partially-approved

#83 GH-83 Add sentry integration
  build.gradle.kts
  src/main/java/com/eternalcode/discordapp/DiscordApp.java
  src/main/java/com/eternalcode/discordapp/config/AppConfig.java
Labels: PR: reviewed-approved

#84 GH-84 Use exist http client and fix intents
  src/main/java/com/eternalcode/discordapp/DiscordApp.java
Labels: PR: partially-approved

#85 GH-85 Change github request time 5 -> 15
  src/main/java/com/eternalcode/discordapp/DiscordApp.java
Labels: PR: partially-approved

#86 GH-86 Add isEmpty to sentry init
  src/main/java/com/eternalcode/discordapp/DiscordApp.java
Labels: PR: reviewed-approved

#90 GH-90 Add if null check
  src/main/java/com/eternalcode/discordapp/review/GitHubReviewService.java
Labels: PR: partially-approved
